import { FOCUS_ARTICLES_1 } from '../article-data/focus-articles-1.mjs';
import { FOCUS_DEPTH_1 } from '../article-data/focus-articles-depth-1.mjs';
import { FOCUS_DEPTH_2 } from '../article-data/focus-articles-depth-2.mjs';
import { FOCUS_DEPTH_3 } from '../article-data/focus-articles-depth-3.mjs';
const SITE='https://xn--k1ae9bxb.online'; const BASE='uvaha-ta-kontsentratsiia'; const LABEL='Увага та концентрація'; const UPDATED_ISO='2026-08-31'; const UPDATED_LABEL='31 серпня 2026 р.';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const safeJson=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const slugify=(v,i)=>String(v||'').toLocaleLowerCase('uk-UA').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zа-яіїєґ0-9]+/gi,'-').replace(/^-+|-+$/g,'')||`section-${i+1}`;
const countWords=a=>[a.title,a.lead,...a.sections.flatMap(s=>[s.heading,...s.paragraphs])].join(' ').trim().split(/\s+/).filter(Boolean).length;
const ALL=FOCUS_ARTICLES_1.map(a=>{const merged={...a,sections:[...a.sections,...(FOCUS_DEPTH_1[a.slug]||[]),...(FOCUS_DEPTH_2[a.slug]||[]),...(FOCUS_DEPTH_3[a.slug]||[])]};return {...merged,wordCount:countWords(merged),readMinutes:Math.max(1,Math.ceil(countWords(merged)/200))}});
function header(){return `<a class="skip-link" href="#content">Перейти до змісту</a><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p class="brand-note">Без осуду. Без спрощених відповідей.</p></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/" aria-current="page">Статті</a><a href="/psykholoham/">Психологам</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer>`}
function shell(title,description,canonical,body,jsonLd=''){return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Лінь</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="uk_UA"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="Лінь">${jsonLd?`<script type="application/ld+json">${safeJson(jsonLd)}</script>`:''}<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body>${header()}<main id="content">${body}</main>${footer()}<script src="/script.js" defer></script></body></html>`}
function renderArticle(article){const canonical=`${SITE}/statti/${BASE}/${article.slug}/`;const jsonLd={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:article.title,description:article.metaDescription,inLanguage:'uk-UA',dateModified:UPDATED_ISO,mainEntityOfPage:{'@type':'WebPage','@id':canonical},author:{'@type':'Organization',name:'Редакція «Лінь»'},publisher:{'@type':'Organization',name:'Лінь',url:`${SITE}/`}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Головна',item:`${SITE}/`},{'@type':'ListItem',position:2,name:'Статті',item:`${SITE}/statti/`},{'@type':'ListItem',position:3,name:LABEL,item:`${SITE}/statti/${BASE}/`},{'@type':'ListItem',position:4,name:article.title,item:canonical}]}]};const toc=article.sections.map((s,i)=>`<a href="#${slugify(s.heading,i)}">${esc(s.heading)}</a>`).join('');const sections=article.sections.map((s,i)=>`<section class="topic-section-block"><h2 id="${slugify(s.heading,i)}">${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');const pos=ALL.findIndex(x=>x.slug===article.slug);const related=[...ALL.slice(pos+1),...ALL.slice(0,pos)].slice(0,3).map(x=>`<article class="article-card"><span>${LABEL} · ${x.readMinutes} хв</span><h3>${esc(x.title)}</h3><p>${esc(x.lead)}</p><a class="button button-primary" href="/statti/${BASE}/${esc(x.slug)}/">Читати статтю →</a></article>`).join('');const body=`<article class="article-page"><header class="article-header shell"><a class="back-link" href="/statti/${BASE}/">← До розділу «${LABEL}»</a><div class="article-meta"><span>${LABEL}</span><span>${article.readMinutes} хв читання</span><span>Оновлено ${UPDATED_LABEL}</span></div><h1>${esc(article.title)}</h1><p class="article-lead">${esc(article.lead)}</p></header><div class="article-layout shell"><aside class="article-toc"><strong>Зміст статті</strong>${toc}</aside><div class="article-body">${sections}</div></div></article><section class="section shell related-section"><div class="section-heading"><p class="section-kicker">Читайте далі</p><h2>Схожі ситуації</h2></div><div class="article-grid">${related}</div></section>`;return shell(article.title,article.metaDescription,canonical,body,jsonLd)}
function renderCatalog(){const jsonLd={'@context':'https://schema.org','@type':'CollectionPage',name:`${LABEL} — практичні статті`,url:`${SITE}/statti/${BASE}/`,inLanguage:'uk-UA',hasPart:ALL.map(a=>({'@type':'Article',name:a.title,url:`${SITE}/statti/${BASE}/${a.slug}/`}))};const cards=ALL.map(a=>`<article class="article-card lin-choice-card topic-library-card"><span>${LABEL} · ${a.readMinutes} хв</span><h3>${esc(a.title)}</h3><p>${esc(a.lead)}</p><a class="topic-library-button" href="/statti/${BASE}/${a.slug}/">Читати статтю →</a></article>`).join('');const body=`<section class="page-hero shell blank-topic-hero"><p class="eyebrow">${LABEL}</p><h1>Коли важко втримати увагу на важливій справі</h1><p class="page-intro">Телефон, постійні перемикання, внутрішні думки, складне читання та звичка відволікатися можуть підтримувати прокрастинацію навіть після того, як ви вже почали.</p><div class="page-actions"><a class="button button-secondary" href="/prokrastynatsiia/">← До прокрастинації</a></div></section><section class="section shell discipline-picker-list"><section class="library-group"><div class="library-group-heading"><div><p class="section-kicker">Добірка 1</p><h2>Повернути увагу до справи</h2></div></div><div class="article-grid">${cards}</div></section></section>`;return shell(`${LABEL} — практичні статті`,`${ALL.length} практичних статей про відволікання, телефон, читання, перемикання та внутрішні думки.`,`${SITE}/statti/${BASE}/`,body,jsonLd)}
export function handleFocus(req,res){if(String(req.query?.audit||'')==='1'){res.statusCode=200;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('X-Robots-Tag','noindex');return res.end(JSON.stringify({count:ALL.length,articles:ALL.map(a=>({slug:a.slug,title:a.title,words:a.wordCount,minutes:a.readMinutes}))},null,2));}const raw=Array.isArray(req.query?.slug)?req.query.slug[0]:req.query?.slug;const slug=String(raw||'').trim();res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, s-maxage=300, stale-while-revalidate=86400');if(!slug){res.statusCode=200;return res.end(renderCatalog())}const article=ALL.find(a=>a.slug===slug);if(!article){res.statusCode=404;return res.end('Not found')}res.statusCode=200;return res.end(renderArticle(article))}
