const SITE='https://xn--k1ae9bxb.online';
const CATEGORIES={
  lin:{name:'Лінь',path:'/lin/',intro:'Лінь, мотивація, дисципліна та енергія — чотири способи точніше зрозуміти, чому важко діяти.'},
  apatiia:{name:'Апатія',path:'/apatiia/',intro:'Втрата інтересу, щастя і задоволення від життя, важкі емоції та самопочуття.'},
  prokrastynatsiia:{name:'Прокрастинація',path:'/prokrastynatsiia/',intro:'Складний старт, тиск на себе, увага й концентрація та поступові зміни себе.'}
};
const TOPICS=[
  {category:'lin',title:'Лінь',href:'/statti/lin/',desc:'Чому не хочеться діяти навіть тоді, коли справа важлива.'},
  {category:'lin',title:'Мотивація',href:'/statti/motyvatsiia/',desc:'Що робити, коли бажання діяти немає або воно швидко зникає.'},
  {category:'lin',title:'Дисципліна',href:'/statti/dystsyplina/',desc:'Як робити потрібне регулярно без режиму «все або нічого».'},
  {category:'lin',title:'Енергія та сили',href:'/statti/enerhiia-ta-syly/',desc:'Втома, сон, відновлення й ситуації, коли проблема не в силі волі.'},
  {category:'apatiia',title:'Втрата інтересу',href:'/statti/vtrata-interesu/',desc:'Коли перестає цікавити те, що раніше подобалося, і як розрізняти можливі причини.'},
  {category:'apatiia',title:'Як бути щасливим',href:'/statti/shchastia/',desc:'Щастя, задоволення від життя, самоцінність, стосунки та здатність помічати хороше.'},
  {category:'apatiia',title:'Важкі емоції',href:'/statti/vazhki-emotsii/',desc:'Тривога, страх, злість, провина, самотність, втрата та інші стани, з якими важко залишатися наодинці.'},
  {category:'apatiia',title:'Здоров’я та самопочуття',href:'/statti/zdorovia-ta-samopochuttia/',desc:'Як фізичний стан, сон і самопочуття можуть впливати на сили, інтерес і повсякденні справи.'},
  {category:'prokrastynatsiia',title:'Як почати',href:'/statti/yak-pochaty/',desc:'Чому ми відкладаємо старт і як перейти до першої конкретної дії.'},
  {category:'prokrastynatsiia',title:'Тиск на себе',href:'/statti/tysk-na-sebe/',desc:'Страх помилки, перфекціонізм, дедлайни та завищені вимоги до себе.'},
  {category:'prokrastynatsiia',title:'Увага та концентрація',href:'/statti/uvaha-ta-kontsentratsiia/',desc:'Телефон, відволікання, інформаційний шум і труднощі з утриманням уваги.'},
  {category:'prokrastynatsiia',title:'Як змінити себе',href:'/statti/yak-zminyty-sebe/',desc:'Як перевіряти звичні пояснення своєї поведінки й поступово змінювати те, що заважає.'}
];
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function safeJson(v){return JSON.stringify(v).replace(/</g,'\\u003c')}
function topicCards(items){return items.map(x=>`<a class="article-card" href="${esc(x.href)}"><h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p></a>`).join('\n')}
function categoryCards(){return Object.values(CATEGORIES).map((x,i)=>`<a class="topic-link" href="${x.path}"><span class="topic-number">0${i+1}</span><span><h3>${esc(x.name)}</h3><p>${esc(x.intro)}</p></span><span class="topic-arrow" aria-hidden="true">→</span></a>`).join('\n')}
function renderPage(key=''){const category=CATEGORIES[key]||null;const items=category?TOPICS.filter(x=>x.category===key):[];const path=category?category.path:'/statti/';const canonical=`${SITE}${path}`;const title=category?`${category.name} — 4 підблоки | Лінь`:'Статті | Лінь';const description=category?`${category.name}: чотири актуальні підблоки.`:'Три розділи в порядку: Лінь, Апатія, Прокрастинація. У кожному — чотири підблоки.';const jsonLd={'@context':'https://schema.org','@type':'CollectionPage',name:category?`${category.name}: підблоки`:'Статті сайту «Лінь»',url:canonical,inLanguage:'uk-UA',hasPart:category?items.map(x=>({'@type':'CollectionPage',name:x.title,url:`${SITE}${x.href}`})):Object.values(CATEGORIES).map(x=>({'@type':'CollectionPage',name:x.name,url:`${SITE}${x.path}`}))};return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${canonical}"><script type="application/ld+json">${safeJson(jsonLd)}</script><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body><a class="skip-link" href="#content">Перейти до змісту</a><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p class="brand-note">Без осуду. Без спрощених відповідей.</p></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/" aria-current="page">Статті</a><a href="/psykholoham/">Психологам</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header><main id="content"><section class="page-hero shell"><p class="eyebrow">${category?esc(category.name):'Статті'}</p><h1>${category?esc(category.name):'Оберіть розділ'}</h1><p class="page-intro">${category?esc(category.intro):'1. Лінь · 2. Апатія · 3. Прокрастинація'}</p>${category?'<div class="page-actions"><a class="button button-secondary" href="/statti/">← До розділів</a></div>':''}</section><section class="section shell topic-choice-section">${category?`<div class="article-grid">${topicCards(items)}</div>`:`<div class="topic-list">${categoryCards()}</div>`}</section></main><footer class="site-footer"><div class="shell footer-grid"><div class="footer-brand"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p>Український простір про лінь, апатію та прокрастинацію.</p></div><nav class="footer-nav"><strong>Розділи</strong><a href="/lin/">Лінь</a><a href="/apatiia/">Апатія</a><a href="/prokrastynatsiia/">Прокрастинація</a></nav></div><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer><script src="/script.js" defer></script></body></html>`}
export default function handler(req,res){const key=String(req.query?.category||'').trim();if(key&&!CATEGORIES[key])return res.status(404).send('Category not found');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('Vercel-CDN-Cache-Control','no-store');return res.status(200).send(renderPage(key))}
