import { readFileSync } from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const SITE='https://xn--k1ae9bxb.online';
const ITEMS=[
['chomu-prokydaiusia-vtomlenym-pislia-snu','Чому прокидаюся втомленим навіть після 8 годин сну','Як перевірити тривалість і якість сну, нічні пробудження та денну сонливість.'],
['yak-nalahodyty-rezhym-snu','Як налагодити режим сну','Як стабілізувати підйом, ранкове світло й вечірній сценарій без різкого перевороту графіка.'],
['yak-shvydko-zasnuty-bez-likiv','Як швидко заснути без ліків','Що робити, коли сон не приходить: менше боротьби, спокійний сценарій і межі самодопомоги.'],
['chomu-vazhko-prokynutysia-vrantsi','Чому важко прокидатися вранці','Як відрізнити недосип, нестабільний режим і стійку денну сонливість.'],
['chomu-khochetsia-spaty-pislia-yizhi','Чому після їжі хочеться спати','Коли післяобідній спад може бути звичайним і що перевірити при сильній сонливості.'],
['chomu-bolyt-holova-i-nemaie-syl','Головний біль і немає сил: що перевірити','Як оцінити сон, воду, їжу, повторюваність і тривожні ознаки без самодіагностики.'],
['chomu-krutytsia-holova-i-slabkist','Крутиться голова і слабкість: що робити','Безпечні перші дії, точний опис запаморочення і ознаки, з якими не варто чекати.'],
['yak-vidnovytysia-pislia-nedosypu','Як відновитися після недосипу','Як пройти день безпечніше, використати відпочинок і не зламати наступну ніч.'],
['chomu-nemaie-syl-pislia-khvoroby','Немає сил після хвороби: як відновлюватися','Як повертати навантаження поступово й оцінювати динаміку відновлення.'],
['chomu-nemaie-apetytu-i-syl','Немає апетиту і сил: що перевірити','Як підтримати базове харчування, оцінити тривалість і не пропустити ситуації для консультації.']
].map(([slug,title,desc])=>({slug,title,desc}));
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const slugify=(v,i)=>String(v||'').toLocaleLowerCase('uk-UA').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zа-яіїєґ0-9]+/gi,'-').replace(/^-+|-+$/g,'')||`section-${i+1}`;
function header(){return `<a class="skip-link" href="#content">Перейти до змісту</a><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p class="brand-note">Без осуду. Без спрощених відповідей.</p></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/" aria-current="page">Статті</a><a href="/psykholoham/">Психологам</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer>`}
function shell(title,desc,canonical,body){return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Лінь</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${canonical}"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body>${header()}<main id="content">${body}</main>${footer()}<script src="/script.js" defer></script></body></html>`}
function load(slug){const source=readFileSync(path.join(ROOT,'article-data',`${slug}.js`),'utf8');const sandbox={window:{}};vm.runInNewContext(source,sandbox,{timeout:1000});return sandbox.window.HABITTEEN_LONG_ARTICLE}
function catalog(){const cards=ITEMS.map((x,i)=>`<article class="article-card lin-choice-card topic-library-card"><span>Здоров’я та самопочуття · ${i<4?10:9} хв</span><h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p><a class="topic-library-button" href="/statti/zdorovia-ta-samopochuttia/${x.slug}/">Читати статтю →</a></article>`).join('');const body=`<section class="page-hero shell blank-topic-hero"><p class="eyebrow">Здоров’я та самопочуття</p><h1>Коли самопочуття забирає сили й бажання діяти</h1><p class="page-intro">10 практичних матеріалів про сон, ранкову втому, слабкість, запаморочення, відновлення після хвороби та інші ситуації, де важливо не плутати самопочуття з «лінню».</p><div class="page-actions"><a class="button button-secondary" href="/apatiia/">← До розділу «Апатія»</a></div></section><section class="section shell"><div class="article-grid">${cards}</div></section>`;return shell('Здоров’я та самопочуття — 10 практичних статей','Сон, слабкість, ранкова втома, запаморочення та відновлення: 10 матеріалів із межами самодопомоги.',`${SITE}/statti/zdorovia-ta-samopochuttia/`,body)}
function articlePage(item,a){const toc=a.sections.map((s,i)=>`<a href="#${slugify(s.heading,i)}">${esc(s.heading)}</a>`).join('');const sections=a.sections.map((s,i)=>`<section class="topic-section-block"><h2 id="${slugify(s.heading,i)}">${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');const practice=a.practice?.length?`<section class="topic-section-block"><h2>Коротка практика</h2><ol class="check-list">${a.practice.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>`:'';const faq=a.faq?.length?`<section class="topic-section-block"><h2>Поширені запитання</h2>${a.faq.map(x=>`<h3>${esc(x.q)}</h3><p>${esc(x.a)}</p>`).join('')}</section>`:'';const body=`<article class="article-page"><header class="article-header shell"><a class="back-link" href="/statti/zdorovia-ta-samopochuttia/">← До «Здоров’я та самопочуття»</a><div class="article-meta"><span>Здоров’я та самопочуття</span><span>${a.updated||'30 серпня 2026 р.'}</span></div><h1>${esc(a.title)}</h1><p class="article-lead">${esc(a.lead)}</p></header><div class="article-layout shell"><aside class="article-toc"><strong>Зміст статті</strong>${toc}</aside><div class="article-body"><p>${esc(a.intro||'')}</p>${sections}${practice}${faq}</div></div></article>`;return shell(a.title,item.desc,`${SITE}/statti/zdorovia-ta-samopochuttia/${item.slug}/`,body)}
export default function handler(req,res){const slug=String(req.query?.slug||'').trim();res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, s-maxage=300, stale-while-revalidate=86400');if(!slug)return res.status(200).send(catalog());const item=ITEMS.find(x=>x.slug===slug);if(!item)return res.status(404).send('Not found');return res.status(200).send(articlePage(item,load(slug)))}