import { handleEnergy } from '../lib/energy-render.mjs';
import { MOTIVATION_ARTICLES_1 } from '../article-data/motivation-articles-1.mjs';
import { MOTIVATION_ARTICLES_2 } from '../article-data/motivation-articles-2.mjs';
import { MOTIVATION_ARTICLES_3 } from '../article-data/motivation-articles-3.mjs';
import { MOTIVATION_ARTICLES_4 } from '../article-data/motivation-articles-4.mjs';
import { DISCIPLINE_ARTICLES } from '../article-data/discipline-articles-1.mjs';
import { DISCIPLINE_ARTICLES_2 } from '../article-data/discipline-articles-2.mjs';
import { DISCIPLINE_ARTICLES_3 } from '../article-data/discipline-articles-3.mjs';
import { DISCIPLINE_DEPTH } from '../article-data/discipline-articles-depth.mjs';
import { DISCIPLINE_DEPTH_2 } from '../article-data/discipline-articles-depth-2.mjs';
import { START_ARTICLES } from '../article-data/start-articles.mjs';
import { FIVE_MINUTE_ARTICLE } from '../article-data/start-five-minute.mjs';
const MOTIVATION_ARTICLES=[...MOTIVATION_ARTICLES_1,...MOTIVATION_ARTICLES_2,...MOTIVATION_ARTICLES_3,...MOTIVATION_ARTICLES_4].filter(a=>a.slug!=='yak-dovodyty-spravy-do-kintsia');
const DISCIPLINE_BASE=[...DISCIPLINE_ARTICLES,...DISCIPLINE_ARTICLES_2,...DISCIPLINE_ARTICLES_3];
const DISCIPLINE_LONG=DISCIPLINE_BASE.map(a=>({...a,sections:[...a.sections,...(DISCIPLINE_DEPTH[a.slug]||[]),...(DISCIPLINE_DEPTH_2[a.slug]||[])]}));
const START_VISIBLE=[...START_ARTICLES.filter(a=>a.slug!=='yak-povernutysia-do-spravy-pislia-zryvu'),FIVE_MINUTE_ARTICLE];
const SITE='https://xn--k1ae9bxb.online'; const UPDATED_ISO='2026-08-30'; const UPDATED_LABEL='30 серпня 2026 р.';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const safeJson=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const slugify=(v,i)=>String(v||'').toLocaleLowerCase('uk-UA').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zа-яіїєґ0-9]+/gi,'-').replace(/^-+|-+$/g,'')||`section-${i+1}`;
function header(){return `<a class="skip-link" href="#content">Перейти до змісту</a><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p class="brand-note">Без осуду. Без спрощених відповідей.</p></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/" aria-current="page">Статті</a><a href="/psykholoham/">Психологам</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer>`}
function shell(title,description,canonical,body,jsonLd=''){return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Лінь</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="uk_UA"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}">${jsonLd?`<script type="application/ld+json">${safeJson(jsonLd)}</script>`:''}<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body>${header()}<main id="content">${body}</main>${footer()}<script src="/script.js" defer></script></body></html>`}
function config(type){if(type==='discipline')return{label:'Дисципліна',base:'dystsyplina',all:DISCIPLINE_LONG,parent:'/lin/'};if(type==='start')return{label:'Як почати',base:'yak-pochaty',all:START_VISIBLE,parent:'/prokrastynatsiia/'};return{label:'Мотивація',base:'motyvatsiia',all:MOTIVATION_ARTICLES,parent:'/lin/'};}
function renderArticle(article,type){const c=config(type);const canonical=`${SITE}/statti/${c.base}/${article.slug}/`;const jsonLd={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:article.title,description:article.metaDescription,inLanguage:'uk-UA',dateModified:UPDATED_ISO,mainEntityOfPage:{'@type':'WebPage','@id':canonical},author:{'@type':'Organization',name:'Редакція «Лінь»'},publisher:{'@type':'Organization',name:'Лінь',url:`${SITE}/`}}, {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Головна',item:`${SITE}/`},{'@type':'ListItem',position:2,name:'Статті',item:`${SITE}/statti/`},{'@type':'ListItem',position:3,name:c.label,item:`${SITE}/statti/${c.base}/`},{'@type':'ListItem',position:4,name:article.title,item:canonical}]}]};const toc=article.sections.map((s,i)=>`<a href="#${slugify(s.heading,i)}">${esc(s.heading)}</a>`).join('');const sections=article.sections.map((s,i)=>`<section class="topic-section-block"><h2 id="${slugify(s.heading,i)}">${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');const pos=c.all.findIndex(x=>x.slug===article.slug);const related=[...c.all.slice(pos+1),...c.all.slice(0,pos)].slice(0,3).map(x=>`<article class="article-card"><span>${c.label} · ${x.readMinutes} хв</span><h3>${esc(x.title)}</h3><p>${esc(x.lead)}</p><a class="button button-primary" href="/statti/${c.base}/${esc(x.slug)}/">Читати статтю →</a></article>`).join('');const body=`<article class="article-page"><header class="article-header shell"><a class="back-link" href="/statti/${c.base}/">← До розділу «${c.label}»</a><div class="article-meta"><span>${c.label}</span><span>${article.readMinutes} хв читання</span><span>Оновлено ${UPDATED_LABEL}</span></div><h1>${esc(article.title)}</h1><p class="article-lead">${esc(article.lead)}</p></header><div class="article-layout shell"><aside class="article-toc"><strong>Зміст статті</strong>${toc}</aside><div class="article-body">${sections}<section class="topic-section-block"><h2>Маленький крок після читання</h2><p>Не намагайтеся виконати всі поради одразу. Оберіть одну дію, яку можна завершити сьогодні за 10–30 хвилин, і після неї заново оцініть, що заважає рухатися далі.</p></section></div></div></article><section class="section shell related-section"><div class="section-heading"><p class="section-kicker">Читайте далі</p><h2>Схожі ситуації</h2></div><div class="article-grid">${related}</div></section>`;return shell(article.title,article.metaDescription,canonical,body,jsonLd)}
function renderCatalog(items,label,base,intro,parent){const groups=[];for(let n=0;n<items.length;n+=5)groups.push(items.slice(n,n+5));const sections=groups.map((group,i)=>`<section class="library-group"><div class="library-group-heading"><div><p class="section-kicker">Добірка ${i+1}</p><h2>${i===0?'Повернутися до дії':'Інші ситуації старту'}</h2></div></div><div class="article-grid">${group.map(a=>`<article class="article-card lin-choice-card topic-library-card"><span>${label} · ${a.readMinutes||8} хв</span><h3>${esc(a.title)}</h3><p>${esc(a.lead)}</p><a class="topic-library-button" href="/statti/${base}/${a.slug}/">Читати статтю →</a></article>`).join('')}</div></section>`).join('');const listJson={'@context':'https://schema.org','@type':'CollectionPage',name:`${label} — практичні статті`,url:`${SITE}/statti/${base}/`,inLanguage:'uk-UA',hasPart:items.map(a=>({'@type':'Article',name:a.title,url:`${SITE}/statti/${base}/${a.slug}/`}))};const body=`<section class="page-hero shell blank-topic-hero"><p class="eyebrow">${label}</p><h1>Знайди ситуацію, яка схожа на твою</h1><p class="page-intro">${intro}</p><div class="page-actions"><a class="button button-secondary" href="${parent}">← До розділу</a></div></section><section class="section shell discipline-picker-list">${sections}</section>`;return shell(`${label} — практичні статті`,`${items.length} практичних статей про те, як перейти від відкладання до першої реальної дії.`,`${SITE}/statti/${base}/`,body,listJson)}
export default function handler(req,res){const category=String(req.query?.category||'');if(category==='energy')return handleEnergy(req,res);const raw=Array.isArray(req.query?.slug)?req.query.slug[0]:req.query?.slug;const slug=String(raw||'').trim();if(category==='motivation'&&!slug){res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(renderCatalog(MOTIVATION_ARTICLES,'Мотивація','motyvatsiia','Як працювати з бажанням діяти, коли воно нестабільне: старт, сенс, винагорода, повернення після паузи та різні життєві ситуації.','/lin/'))}if(category==='discipline'&&!slug){res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(renderCatalog(DISCIPLINE_LONG,'Дисципліна','dystsyplina','Як виконувати власні рішення у звичайні дні без режиму «все або нічого».','/lin/'))}if(category==='start'&&!slug){res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(renderCatalog(START_VISIBLE,'Як почати','yak-pochaty','Коли справа вже відкладалася, накопичилася або до неї важко повернутися: окремі сценарії для навчання, роботи, завалу справ і повторного старту.','/prokrastynatsiia/'))}const type=category==='discipline'?'discipline':category==='start'?'start':'motivation';const all=config(type).all;const article=all.find(a=>a.slug===slug);if(!article){res.statusCode=404;return res.end('Not found')}res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, s-maxage=300, stale-while-revalidate=86400');return res.end(renderArticle(article,type))}
