import { handleEnergy } from '../lib/energy-render.mjs';
import { MOTIVATION_ARTICLES_1 } from '../article-data/motivation-articles-1.mjs';
import { MOTIVATION_ARTICLES_2 } from '../article-data/motivation-articles-2.mjs';
import { MOTIVATION_ARTICLES_3 } from '../article-data/motivation-articles-3.mjs';
import { MOTIVATION_ARTICLES_4 } from '../article-data/motivation-articles-4.mjs';
import { DISCIPLINE_ARTICLES } from '../article-data/discipline-articles-1.mjs';
import { DISCIPLINE_ARTICLES_2 } from '../article-data/discipline-articles-2.mjs';
import { DISCIPLINE_ARTICLES_3 } from '../article-data/discipline-articles-3.mjs';
import { DISCIPLINE_DEPTH } from '../article-data/discipline-articles-depth.mjs';
import { DISCIPLINE_DEPTH_2 } from '../article-data/discipline-articles-depth-2.mjs';
const MOTIVATION_ARTICLES=[...MOTIVATION_ARTICLES_1,...MOTIVATION_ARTICLES_2,...MOTIVATION_ARTICLES_3,...MOTIVATION_ARTICLES_4].filter(a=>a.slug!=='yak-dovodyty-spravy-do-kintsia');
const DISCIPLINE_BASE=[...DISCIPLINE_ARTICLES,...DISCIPLINE_ARTICLES_2,...DISCIPLINE_ARTICLES_3];
const DISCIPLINE_LONG=DISCIPLINE_BASE.map(a=>({...a,sections:[...a.sections,...(DISCIPLINE_DEPTH[a.slug]||[]),...(DISCIPLINE_DEPTH_2[a.slug]||[])]}));
const SITE='https://xn--k1ae9bxb.online'; const UPDATED_ISO='2026-08-28'; const UPDATED_LABEL='28 серпня 2026 р.';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const safeJson=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const slugify=(v,i)=>String(v||'').toLocaleLowerCase('uk-UA').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zа-яіїєґ0-9]+/gi,'-').replace(/^-+|-+$/g,'')||`section-${i+1}`;
function header(){return `<a class="skip-link" href="#content">Перейти до змісту</a><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p class="brand-note">Без осуду. Без спрощених відповідей.</p></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/" aria-current="page">Статті</a><a href="/psykholoham/">Психологам</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer>`}
function shell(title,description,canonical,body,jsonLd=''){return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Лінь</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${canonical}">${jsonLd?`<script type="application/ld+json">${safeJson(jsonLd)}</script>`:''}<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body>${header()}<main id="content">${body}</main>${footer()}<script src="/script.js" defer></script></body></html>`}
function renderArticle(article,type){const isD=type==='discipline';const label=isD?'Дисципліна':'Мотивація';const base=isD?'dystsyplina':'motyvatsiia';const all=isD?DISCIPLINE_LONG:MOTIVATION_ARTICLES;const canonical=`${SITE}/statti/${base}/${article.slug}/`;const jsonLd={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:article.title,description:article.metaDescription,inLanguage:'uk-UA',dateModified:UPDATED_ISO,mainEntityOfPage:{'@type':'WebPage','@id':canonical},author:{'@type':'Organization',name:'Редакція «Лінь»'},publisher:{'@type':'Organization',name:'Лінь',url:`${SITE}/`}}, {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Головна',item:`${SITE}/`},{'@type':'ListItem',position:2,name:'Статті',item:`${SITE}/statti/`},{'@type':'ListItem',position:3,name:label,item:`${SITE}/statti/${base}/`},{'@type':'ListItem',position:4,name:article.title,item:canonical}]}]};const toc=article.sections.map((s,i)=>`<a href="#${slugify(s.heading,i)}">${esc(s.heading)}</a>`).join('');const sections=article.sections.map((s,i)=>`<section class="topic-section-block"><h2 id="${slugify(s.heading,i)}">${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');const related=all.filter(x=>x.slug!==article.slug).slice(0,3).map(x=>`<article class="article-card"><span>${label} · ${x.readMinutes} хв</span><h3>${esc(x.title)}</h3><p>${esc(x.lead)}</p><a class="button button-primary" href="/statti/${base}/${esc(x.slug)}/">Читати статтю →</a></article>`).join('');const body=`<article class="article-page"><header class="article-header shell"><a class="back-link" href="/statti/${base}/">← До розділу «${label}»</a><div class="article-meta"><span>${label}</span><span>${article.readMinutes} хв читання</span><span>Оновлено ${UPDATED_LABEL}</span></div><h1>${esc(article.title)}</h1><p class="article-lead">${esc(article.lead)}</p></header><div class="article-layout shell"><aside class="article-toc"><strong>Зміст статті</strong>${toc}</aside><div class="article-body">${sections}</div></div></article><section class="section shell related-section"><div class="section-heading"><p class="section-kicker">Ще про ${label.toLocaleLowerCase('uk-UA')}</p><h2>Схожі ситуації</h2></div><div class="article-grid">${related}</div></section>`;return shell(article.title,article.metaDescription,canonical,body,jsonLd)}
function renderCatalog(items,label,base,intro){const groups=[0,5,10,15].map(n=>items.slice(n,n+5));const sections=groups.map((group,i)=>`<section class="library-group"><div class="library-group-heading"><div><p class="section-kicker">Ситуації ${i+1}</p><h2>${label}: добірка ${i+1}</h2></div></div><div class="article-grid">${group.map(a=>`<article class="article-card lin-choice-card topic-library-card"><span>${label} · ${a.readMinutes||8} хв</span><h3>${esc(a.title)}</h3><p>${esc(a.lead)}</p><a class="topic-library-button" href="/statti/${base}/${a.slug}/">Читати статтю →</a></article>`).join('')}</div></section>`).join('');const body=`<section class="page-hero shell blank-topic-hero"><p class="eyebrow">${label}</p><h1>Знайди ситуацію, яка схожа на твою</h1><p class="page-intro">${intro}</p><div class="page-actions"><a class="button button-secondary" href="/lin/">← До розділу «Лінь»</a></div></section><section class="section shell discipline-picker-list">${sections}</section>`;return shell(`${label} — практичні статті`,`${items.length} практичних статей про ${label.toLocaleLowerCase('uk-UA')}.`,`${SITE}/statti/${base}/`,body)}
export default function handler(req,res){const category=String(req.query?.category||'');if(category==='energy')return handleEnergy(req,res);const raw=Array.isArray(req.query?.slug)?req.query.slug[0]:req.query?.slug;const slug=String(raw||'').trim();if(category==='motivation'&&!slug){res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(renderCatalog(MOTIVATION_ARTICLES,'Мотивація','motyvatsiia','Як працювати з бажанням діяти, коли воно нестабільне: старт, сенс, винагорода, повернення після паузи та різні життєві ситуації.'))}if(category==='discipline'&&!slug){res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(renderCatalog(DISCIPLINE_LONG,'Дисципліна','dystsyplina','Як виконувати власні рішення у звичайні дні без режиму «все або нічого».'))}const type=category==='discipline'?'discipline':'motivation';const all=type==='discipline'?DISCIPLINE_LONG:MOTIVATION_ARTICLES;const article=all.find(a=>a.slug===slug);if(!article){res.statusCode=404;return res.end('Not found')}res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, s-maxage=300, stale-while-revalidate=86400');return res.end(renderArticle(article,type))}
