import { handleEnergy } from '../lib/energy-render.mjs';
import { MOTIVATION_ARTICLES_1 } from '../article-data/motivation-articles-1.mjs';
import { MOTIVATION_ARTICLES_2 } from '../article-data/motivation-articles-2.mjs';
import { MOTIVATION_ARTICLES_3 } from '../article-data/motivation-articles-3.mjs';
import { MOTIVATION_ARTICLES_4 } from '../article-data/motivation-articles-4.mjs';
import { DISCIPLINE_ARTICLES } from '../article-data/discipline-articles-1.mjs';
import { DISCIPLINE_ARTICLES_2 } from '../article-data/discipline-articles-2.mjs';
import { DISCIPLINE_ARTICLES_3 } from '../article-data/discipline-articles-3.mjs';
import { DISCIPLINE_DEPTH } from '../article-data/discipline-articles-depth.mjs';
import { DISCIPLINE_DEPTH_2 } from '../article-data/discipline-articles-depth-2.mjs';
const MOTIVATION_ARTICLES=[...MOTIVATION_ARTICLES_1,...MOTIVATION_ARTICLES_2,...MOTIVATION_ARTICLES_3,...MOTIVATION_ARTICLES_4].filter(a=>a.slug!=='yak-dovodyty-spravy-do-kintsia');
const DISCIPLINE_BASE=[...DISCIPLINE_ARTICLES,...DISCIPLINE_ARTICLES_2,...DISCIPLINE_ARTICLES_3];
const DISCIPLINE_LONG=DISCIPLINE_BASE.map(a=>({...a,sections:[...a.sections,...(DISCIPLINE_DEPTH[a.slug]||[]),...(DISCIPLINE_DEPTH_2[a.slug]||[])]}));
const SITE='https://xn--k1ae9bxb.online';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
function header(){return `<a class="skip-link" href="#content">Перейти до змісту</a><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a><p class="brand-note">Без осуду. Без спрощених відповідей.</p></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/" aria-current="page">Статті</a><a href="/psykholoham/">Психологам</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer>`}
function shell(title,description,canonical,body){return `<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Лінь</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="${canonical}"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body>${header()}<main id="content">${body}</main>${footer()}<script src="/script.js" defer></script></body></html>`}
function catalog(items,label,base,intro){const groups=[0,5,10,15].map(n=>items.slice(n,n+5));const sections=groups.map((g,i)=>`<section class="library-group"><div class="library-group-heading"><div><p class="section-kicker">Ситуації ${i+1}</p><h2>${label}: добірка ${i+1}</h2></div></div><div class="article-grid">${g.map(a=>`<article class="article-card lin-choice-card topic-library-card"><span>${label} · ${a.readMinutes||8} хв</span><h3>${esc(a.title)}</h3><p>${esc(a.lead)}</p><a class="topic-library-button" href="/statti/${base}/${a.slug}/">Читати статтю →</a></article>`).join('')}</div></section>`).join('');return shell(`${label} — практичні статті`,`${items.length} практичних статей про ${label.toLocaleLowerCase('uk-UA')}.`,`${SITE}/statti/${base}/`,`<section class="page-hero shell blank-topic-hero"><p class="eyebrow">${label}</p><h1>Знайди ситуацію, яка схожа на твою</h1><p class="page-intro">${intro}</p><div class="page-actions"><a class="button button-secondary" href="/lin/">← До розділу «Лінь»</a></div></section><section class="section shell discipline-picker-list">${sections}</section>`)}
function renderArticle(article,type){const label=type==='discipline'?'Дисципліна':'Мотивація';const base=type==='discipline'?'dystsyplina':'motyvatsiia';const body=`<article class="article-page"><header class="article-header shell"><a class="back-link" href="/statti/${base}/">← До розділу «${label}»</a><div class="article-meta"><span>${label}</span><span>${article.readMinutes||8} хв читання</span></div><h1>${esc(article.title)}</h1><p class="article-lead">${esc(article.lead)}</p></header><div class="article-layout shell"><div class="article-body">${article.sections.map(s=>`<section class="topic-section-block"><h2>${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('')}</div></div></article>`;return shell(article.title,article.metaDescription,`${SITE}/statti/${base}/${article.slug}/`,body)}
export default function handler(req,res){const category=String(req.query?.category||'');if(category==='energy')return handleEnergy(req,res);const raw=Array.isArray(req.query?.slug)?req.query.slug[0]:req.query?.slug;const slug=String(raw||'').trim();if(category==='motivation'&&!slug){res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(catalog(MOTIVATION_ARTICLES,'Мотивація','motyvatsiia','Як працювати з бажанням діяти, коли воно нестабільне: старт, сенс, винагорода, повернення після паузи та різні життєві ситуації.'))}if(category==='discipline'&&!slug){res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(catalog(DISCIPLINE_LONG,'Дисципліна','dystsyplina','Як виконувати власні рішення у звичайні дні без режиму «все або нічого».'))}const type=category==='discipline'?'discipline':'motivation';const all=type==='discipline'?DISCIPLINE_LONG:MOTIVATION_ARTICLES;const article=all.find(a=>a.slug===slug);if(!article)return res.status(404).send('Not found');res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, max-age=0, s-maxage=300, stale-while-revalidate=86400');return res.status(200).send(renderArticle(article,type))}
