import { YAK_POCHATY_ARTICLES_1 } from '../article-data/yak-pochaty-articles-1.mjs';
import { YAK_POCHATY_ARTICLES_2 } from '../article-data/yak-pochaty-articles-2.mjs';
const SITE='https://xn--k1ae9bxb.online';
const ARTICLES=[...YAK_POCHATY_ARTICLES_1,...YAK_POCHATY_ARTICLES_2];
const esc=(v)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const json=(v)=>JSON.stringify(v).replace(/</g,'\\u003c');
const layout=(title,description,canonical,body,ld)=>`<!doctype html><html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Лінь</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${canonical}"><meta property="og:type" content="article"><meta property="og:locale" content="uk_UA"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${json(ld)}</script><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/refresh.css"></head><body><header class="site-header"><div class="shell brand-row"><a class="brand" href="/"><span class="brand-mark">Л</span><span>Лінь</span></a></div><div class="nav-wrap"><nav class="site-nav shell"><a href="/">Головна</a><a href="/statti/">Статті</a><a href="/pro-sait/">Про сайт</a><a href="/bezpeka/">Безпека</a></nav></div></header><main id="content">${body}</main><footer class="site-footer"><div class="shell footer-bottom"><span>© 2026 Лінь</span><span>Матеріали для самоосвіти, а не самодіагностики</span></div></footer></body></html>`;
function catalog(){const canonical=`${SITE}/statti/yak-pochaty/`;const cards=ARTICLES.map(a=>`<article class="article-card"><p class="eyebrow">Як почати · ${a.readMinutes||8} хв</p><h2>${esc(a.title)}</h2><p>${esc(a.metaDescription)}</p><a href="/statti/yak-pochaty/${esc(a.slug)}/">Читати статтю →</a></article>`).join('');return layout('Як почати — статті про старт без прокрастинації','10 практичних статей про те, як перестати відкладати, почати роботу, навчання, неприємні та важливі справи.',canonical,`<section class="page-hero shell"><p class="eyebrow">Прокрастинація</p><h1>Як почати</h1><p class="page-intro">Коли проблема виникає ще до першої реальної дії: різні причини відкладання, конкретні сценарії та маленькі способи перевірити, що допомагає саме вам.</p><div class="page-actions"><a class="button button-secondary" href="/prokrastynatsiia/">← До прокрастинації</a></div></section><section class="section shell"><div class="article-grid">${cards}</div></section>`,{'@context':'https://schema.org','@type':'CollectionPage',name:'Як почати',url:canonical,inLanguage:'uk-UA',hasPart:ARTICLES.map(a=>({'@type':'Article',headline:a.title,url:`${canonical}${a.slug}/`}))});}
function article(a){const canonical=`${SITE}/statti/yak-pochaty/${a.slug}/`;const sections=(a.sections||[]).map(s=>`<section><h2>${esc(s.heading)}</h2>${(s.paragraphs||[]).map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');const faq=(a.faq||[]).length?`<section><h2>Короткі відповіді</h2>${a.faq.map(x=>`<h3>${esc(x.q)}</h3><p>${esc(x.a)}</p>`).join('')}</section>`:'';return layout(a.title,a.metaDescription,canonical,`<article class="article-page shell"><p class="eyebrow"><a href="/statti/yak-pochaty/">Як почати</a> · ${a.readMinutes||8} хв</p><h1>${esc(a.title)}</h1><p class="page-intro">${esc(a.lead)}</p>${sections}${faq}<section class="article-cta"><h2>Не шукайте ідеального старту</h2><p>Оберіть одну ситуацію з цієї статті й перевірте найменший наступний крок сьогодні. Мета — отримати реальний досвід старту, а не ще один план.</p><a href="/statti/yak-pochaty/">← Інші статті «Як почати»</a></section></article>`,{'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.metaDescription,url:canonical,inLanguage:'uk-UA',dateModified:'2026-08-30',mainEntityOfPage:canonical});}
export default function handler(req,res){const slug=String(req.query?.slug||'').trim();const html=slug?(()=>{const a=ARTICLES.find(x=>x.slug===slug);return a?article(a):null})():catalog();if(!html){res.statusCode=404;res.setHeader('Content-Type','text/plain; charset=utf-8');res.end('Article not found');return;}res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.end(html);}
